---
- name: Install minimal GNOME Desktop components
  apt:
    pkg:
      - gnome-shell
      - gnome-terminal
      - gdm3
    state: present

- name: Ensure GDM3 is enabled and started
  systemctl:
    name: gdm3
    enabled: yes
    state: started
