---
- name: Install Timeshift
  apt:
    pkg:
      - timeshift
      - inotify-tools
    state: present

- name: Configure Timeshift JSON
  copy:
    dest: /etc/timeshift/timeshift.json
    content: |
      {
        "backup_device_uuid": "",
        "parent_directory": "/",
        "do_first_run": "false",
        "btrfs_mode": "false",
        "include_btrfs_home_for_snapshots": "false",
        "include_btrfs_home_for_restore": "false",
        "stop_cron_emails": "true",
        "schedule_monthly": "false",
        "schedule_weekly": "false",
        "schedule_daily": "true",
        "schedule_hourly": "false",
        "schedule_boot": "false",
        "count_monthly": "2",
        "count_weekly": "3",
        "count_daily": "5",
        "count_hourly": "6",
        "count_boot": "5",
        "snapshot_device": "",
        "rrsync_mode": "true"
      }
    mode: '0644'
    force: no

- name: Create initial system snapshot
  command: timeshift --create --comments "Initial Provisioning via Ansible" --tags D
  register: timeshift_result
  changed_when: "'Snapshot created successfully' in timeshift_result.stdout"
  ignore_errors: yes
