---
- name: Check if running on a Physical Machine (Safety)
  ansible.builtin.fail:
    msg: "Aborting: Hardware tuning should not run on a Virtual Machine."
  when: ansible_virtualization_role == "guest"

- name: Optimize Kernel Parameters for NVMe and CPU in GRUB
  ansible.builtin.lineinfile:
    path: /etc/default/grub
    regexp: '^GRUB_CMDLINE_LINUX_DEFAULT='
    line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet splash nvme_core.default_ps_max_latency_us=0 split_lock_detect=off"'
    state: present
  notify: Update GRUB

- name: Install CPU frequency management tools
  apt:
    name: cpufrequtils
    state: present

- name: Set CPU Governor to performance
  lineinfile:
    path: /etc/default/cpufrequtils
    regexp: '^GOVERNOR='
    line: 'GOVERNOR="performance"'
    state: present
  notify: Restart cpufrequtils
