---
- name: Update package cache and upgrade system
  apt:
    update_cache: yes
    upgrade: dist

- name: Install base tools
  apt:
    pkg: [build-essential, fastfetch, htop, hwloc, sudo]

- name: Configure user password and shell
  user:
    name: "{{ main_user }}"
    password: "{{ user_password }}"
    shell: /bin/bash
    groups: sudo
    append: yes

- name: Configure sudoers for {{ main_user }}
  copy:
    content: "{{ main_user }} ALL=(ALL) ALL"
    dest: "/etc/sudoers.d/{{ main_user }}"
    mode: '0440'

- name: Optimize journald log size
  lineinfile:
    path: /etc/systemd/journald.conf
    regexp: "^#?SystemMaxUse="
    line: "SystemMaxUse={{ journal_max_size }}"
  notify: Restart journald
