---
# 1. Hardware Validation (Apenas Hardware Real)
- name: Verify CPU virtualization support (VT-x/AMD-V)
  shell: grep -E 'vmx|svm' /proc/cpuinfo
  register: cpu_virt
  ignore_errors: yes
  changed_when: false

- name: Check BIOS Virtualization status
  fail:
    msg: "ERRO: Virtualização desligada na BIOS. Ative VT-x/SVM na sua Z790!"
  # Só falha se for hardware real E não encontrar as flags de CPU
  when: cpu_virt.rc != 0 and ansible_virtualization_type == 'none'

# 2. Software Installation (Roda em ambos, útil para gerenciar VMs remotas na VM)
- name: Install QEMU and Libvirt tools
  apt:
    pkg:
      - qemu-kvm
      - qemu-system-x86
      - qemu-system-arm
      - qemu-system-aarch64
      - qemu-system-mips
      - qemu-system-ppc
      - qemu-system-s390x
      - qemu-system-riscv
      - qemu-system-alpha
      - qemu-system-sparc
      - qemu-system-m68k
      - qemu-user
      - qemu-guest-agent
      - qemu-utils
      - libvirt-daemon-system
      - libvirt-clients
      - bridge-utils
      - virt-manager
      - ovmf
      - tuned
      - tuned-utils
    state: present

- name: Add user to virtualization groups
  user:
    name: "{{ main_user }}"
    groups:
      - kvm
      - libvirt
    append: yes

- name: Set performance profile
  command: tuned-adm profile virtual-host
  changed_when: false
  # Tuned virtual-host só faz sentido em hosts reais
  when: ansible_virtualization_type == 'none'

- name: Create Libvirt hooks structure
  file:
    path: "/etc/libvirt/hooks/{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - ""
    - "qemu.d"
    - "lxc.d"
    - "network.d"

- name: Create Logical Volume for VMs
  lvol:
    vg: "{{ volume_group }}"
    lv: "{{ vm_lv_name }}"
    size: 100%FREE
    state: present
  # Ignora se o VG não existir (comum em VMs de teste)
  ignore_errors: yes
  when: ansible_virtualization_type == 'none'

- name: Ensure libvirtd is started
  systemd:
    name: libvirtd
    enabled: yes
    state: started
