---
- name: Update PAM
  command: pam-auth-update --package
  changed_when: true

- name: Update Initramfs
  command: update-initramfs -u
  listen: "refresh security"

- name: Reload Systemd
  systemd:
    daemon_reload: yes
